package com.example.bankservice.domain.model.enums;

public enum TransactionType {
    PAYMENT_TRANSACTION,
    CREDIT_MONTHLY_PAYMENT_TRANSACTION,
    CREDIT_APPROVE_TRANSACTION,
    STOCK_TRANSACTION,
    OTC_TRANSACTION,
    PAY_TAX_TRANSACTION,
    MARGIN_TRANSACTION,
}
